;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cljr-slash
        cua-insert-char-rectangle
        exit-recursive-edit
        haml-electric-backspace
        paredit-backward-kill-word
        ))

(setq mc/cmds-to-run-once
      '(
        cua-delete-region
        ))
